### PR TITLE
mallan/catkin build qt5

### PR DESCRIPTION
**Pull request by mallanmba**
fix broken build on Ubuntu 14.04. Adding qt_gui_cpp to catkin find_package caused bizzare link problems downstream with libdl. Adding -ldl to the examples that were failing had no effect. Adding -ldl immediately following RTIDDS_LIBRARIES in knDds, however, inexplicably solves the problem. The RTIDDS_LIBRARIES variable ALREADY includes libdl. Also, the full paths to libraries in the RTIDDS_LIBRARIES are stripped and what makes it into the link link is -lnddscore, etc. Dont know if catkin is munging it or cmake, but this behavior is very very bad. This seems to fix things for now.

### CODE REVIEW

**Comment by hhutz** [comment]
I certainly welcome the merge from trunk. But I am slightly confused about the dl problem.

I just build on my fresh 14.04 install from scratch without this patch and I don't see any failures. Where would those show up?

**Comment by mallanmba** [comment]
The examples in knDds fail to link. Folks at NRC are having compile
problems, too...

**Comment by mallanmba** [comment]
Tested against the 5.2.3 release and it did not display the problem, but the router fix engineering release does.

**Comment by hhutz** [comment]
Okay. That's not pretty, but at least gives a reasonable explanation for this failure happening to some users but not others. Thank you for tracking it down.

**Pull request merged**
